### ISSUE TITLE
Make S1x have its own folder

### ISSUE THREAD

**Issue by SoyRA** [XLabsProject/s1x-client#159]
Currently S1x generates these files in the game folder:
```
__s1Exe (hidden file)
players2\*
s1x\*
```
\
\
I propose that S1x should continue to be installed where the game is, but that everything it generates should be stored in its own folder:
```
s1x.exe
s1x\__s1Exe (well, this one doesn't matter because it's deleted if the game was closed correctly)
s1x\players2\*
```
\
\
Something like FiveM, Plutonium, etc. but not so separate.
You could even make that, if you install the DLCs on `s1x\*` (or `s1x\dlc\*`), you will be able to use them without problems.

**Comment by SoyRA** [comment]
- From `main\*` to `s1x\main\*` : `fs_basegame "main"`
- From `players2\*` to `s1x\players2\*` : `fs_homepath "s1x"`
https://github.com/XLabsProject/s1x-client/blob/edf1d4163960d4846c7c246c70d75ee7feb21126/src/client/component/filesystem.cpp#L47
- From `players2\user\*` to `s1x\players2\user\*` : `return "s1x/players2/user/" + name;`
https://github.com/XLabsProject/s1x-client/blob/edf1d4163960d4846c7c246c70d75ee7feb21126/src/client/game/demonware/services/bdStorage.cpp#L133

Looks like it's able to write the files but it's not able to read them (I only lose the graphics, controls, etc. but not the stats).
I tried it in the 4 modes that appears in the Launcher, but I haven't verified what happens in dedicated server mode.
  \* Oh, and in SP I can't finish the initial cinematic because it says [Insufficient free disk space](https://i.imgur.com/rMcmEnQ.png) (I don't know if it's a problem of the modification I made or the `v1.0.3-2-gedf1d41-dirty` itself).

Since I don't know C++ or even about the game, I probably won't make any progress on this. 🤡

**Comment by mjkzy** [comment]
@SoyRA 
i think ``main\*`` stuff should stay, same for ``players2\*`` as that comes directly from Steam so stuff transfers over nice and smoothly (just avoid people making issues and asking for help)

however, I think ``minidumps\*`` could go to ``s1x\minidumps\*`` instead. i'll write up a quick commit to change that and mention this issue.

**Comment by SoyRA** [comment]
> i think `main\*` stuff should stay, same for `players2\*` as that comes directly from Steam so stuff transfers over nice and smoothly 

And do something like this?
\- If `main\*` and / or `players2\*` exists and is not in `s1x\*`, move it.
 \* Well, `main\*` is already in `s1x\*` (just not in `s1x\main\*`).

**Comment by mjkzy** [comment]
hmm, maybe.

**Comment by diamante0018** [comment]
I disagree with this in almost it's entirety.
Right now with the launcher and the client are running from another folder in addition the script are also in localappdata. There is no reason to change the location of game files since it would differ from other call of duty games and make users look for specific files in an unfamiliar directory.
In the S1x folder I think I would only put client specific files and leave the rest alone.
In addition the client is also clearly not in active development so there is no reason to change the behaviour that all call of duty games have when it comes the location of some folders. But, if Momo wants he may reopen this, I just don't see any valid points.
