### ISSUE TITLE
Can you guys make a mod which allows us to rank up(or level up) with bots in public matches for Advanced Warfare? Please

### ISSUE THREAD

**Issue by Plasmo-Etherium-Sunshine** [XLabsProject/s1x-client#195]
I want to play public matches with bots in Advanced Warfare but can't find anything that would work like Redacted. Let me explain: Redacted is a mod that allows us to play public matches with bots(in Black Ops 2), how you may ask? Well you can't start a public match with only 1 player in the lobby, you need at least 5 players to start the match, what redacted have is a command --> 'xpartygo' which allows us to start a game with an empty lobby and then after the match allows us to add bots by a command 'spawnBot' which is already in your S1x client, this way we can play with bots and also level up as if we were playing with real people! I don't want that you guys make an entire mod and waste your time(I guess you have better things to do) but instead make a command which allows us to override the game and start a match with an empty lobby after then we can easily add bots with the help of the already existing spawnBot command. Thnx if you read my request all the way till here and I'll be very grateful to the developers if they added this feature in the next update. BTW there is a 'xpartygo' command in S1x client but it doesn't do anything. anyway thnx again for the wonderful S1x client !!! :)

**Comment by mjkzy** [comment]
summary:
allow use of xpartygo in public match

**Comment by IMMORTALVASILIY** [comment]
does this really work ?
xpartygo doesn't work for me

**Comment by Plasmo-Etherium-Sunshine** [comment]
thats what i said xpartygo doesn't work in S1x but it does in BO2(Redacted)

**Comment by Plasmo-Etherium-Sunshine** [comment]
Just to remind you its been 11 Days but I haven't lost any faith so take your time and make xpartygo work in the S1x client please.

**Comment by nmjbhoffmann** [comment]
From what I've seen in my testing, even if they added xpartygo, there's an issue where bots freeze when xblive_privatematch is set to 0 anyway. So that's probably why they aren't "_just_ adding the command".

I know it's possible to allow this to work by using an edited playlist that allows you to "find" games with min players of 1 and have bots added to it like with project nova, but to do this with less jank is probably a bit more of an issue.

Either way, iw6x has the exact same issue where bots freeze in comp and it's not fixed yet. I'm guessing it might take a while, so for now PN is the only offline way to deal with bots for now. But at least you can copy your profile between the two till this feature gets added.

**Comment by LeRutY** [comment]
Why did you close this? Has this been added?

**Comment by RCPeterWu** [comment]
> Why did you close this? Has this been added?

No. Still not work.
