### ISSUE TITLE
Binary Mapped Incorrectly

### ISSUE THREAD

**Issue by Sleer23** [XLabsProject/s1x-client#391]
Hello. About a month and a half ago I downloaded advanced warfare on steam I loaded up the s1x client and the single player worked fine but multiplayer game me the error ![image](https://user-images.githubusercontent.com/107884982/174663618-420d2731-3cee-4f73-914d-b34cc5574cb1.jpeg)

The torrent did the same thing. A tech support person on discord helped me attempt to launch s1x without xlabs but same issue. So xlabs is not the issue. Someone please help. 
 ![image](https://user-images.githubusercontent.com/107884982/174663871-bbdf9fe5-964a-4be7-9618-b517b4b32a3c.jpeg)
Windows 10 pro
I5 11600k
Gtx 1660
Asus tuf b560m plus wifi

**Comment by Trippies** [comment]
i have some problem :( idk how to fix it

**Comment by doshisgone** [comment]
i was getting this same crash on windows 11, fixed it by turning off memory integrity in windows defender. i have since then switched back to windows 10 and haven't had this crash since then but it appears to me that memory integrity isn't a thing on windows 10, and as such im not entirely sure what you'd have to turn off to get it to work.

**Comment by diamante0018** [comment]
Has op tried to turn off memory integrity as suggested?

**Comment by diamante0018** [comment]
Please try what was suggested by the other community members.
Unfortunately, this issue doesn't give us any information to work with so I'm going to close it.
Please join our discord server if you need more help.
