### ISSUE TITLE
Server Spawn Bots

### ISSUE THREAD

**Issue by monocolotion** [XLabsProject/s1x-client#571]
There is no documentation on how to automatically generate bots on a dedicated server. Had to spawn the bot through the console.

Any help on this matter would be greatly appreciated. thank you very much in advance

**Comment by diamante0018** [comment]
Hello, when you created this issue, this document should have appeared in front of you [get-help](https://github.com/XLabsProject/s1x-client/blob/develop/.github/ISSUE_TEMPLATE/get-help.md).
Did you try any of the links it suggested?
Because you can spawn bots via scripts but you will not get advice on how to do it here on GitHub.
You must join the XLabs discord and ask in the s1x-modding channel where I'm sure someone will be able to help you out on how to spawn bots with a script.

**Comment by diamante0018** [comment]
Please wait a few days. It will be worth the effort.
In the meantime, I'll let another admin know if there is a way to whitelist you now.

**Comment by monocolotion** [comment]
Thanks

**Comment by monocolotion** [comment]
monocolotion#5175 
My Discord account
