### ISSUE TITLE
Round Based modes bugged on Dedicated Servers with Bots

### ISSUE THREAD

**Issue by BoxOfMysteriez** [XLabsProject/s1x-client#587]
**What are you trying to do?**
Have a full match of a round based mode with bots on a dedicated server

**What problem are you having?**
When attempting to play any round based mode (SnD, Uplink, ect...) the match will fail to proceed past the first round on a dedicated server. The game will simply "pause" after the first round ending kill cam is complete and leave players hanging on an empty screen. 

**What version of S1x are you using?**
Stable Release 2.1.0, also tested latest develop build
Using latest dedicated server scripts

**Anything else we should know?**
Nope, but Thanks for taking a look at the Gun Game issue and Game Mode text issue, can confirm both are fixed when using latest scripts from the "data" folder.

**Comment by bradstv** [comment]
I found the issue and a temp fix for this.
In `maps/mp/gametypes/_gamelogic.gsc`, the `endgame` function and other similar functions, calls `map_restart( 1 );` at the end of the round to go the next. 
Turns out this function is mislabeled in the gsc-tool resolver. It's actually has the right name but is labeled twice so I guess when parsing, it uses the one with the wrong hex id. 
So, changing all the lines in `_gamelogic.gsc` in the s1x data folder that contain `map_restart( 1 );` to `_func_169( 1 );` fixes the issue. (lines 2445, 2526, 2659)
This is more of a temp fix as the real solution would be fixing it in the gsc-tool resolver.
Also, `exitlevel` is labeled twice as well. 

The correct hext ids are:
`map_restart` - 0x169
`exitlevel` - 0x16A

I can make a pull request to the xlabs gsc-tool branch if needed.

**Comment by diamante0018** [comment]
I will notify xensik the gsc-tool owner

**Comment by BoxOfMysteriez** [comment]
Can confirm this does fix the issue, tested all round based modes on a dedicated server and they all worked fine. Thank you for looking into this.

**Comment by diamante0018** [comment]
I will implement the fix in a bit
