### ISSUE TITLE
Exo Zombies Carrier map error

### ISSUE THREAD

**Issue by Leotas97** [XLabsProject/s1x-client#98]
Getting these errors when I try playing on the Carrier map in Exo Zombies.  
It is the only map this happens on, so no it is not my graphics drivers being the issue.

![image](https://user-images.githubusercontent.com/82874051/115372130-97dee400-a198-11eb-9ac4-0afea9691632.png)

**Comment by RetroRemix** [comment]
yeah i have the same issue with the same map

**Comment by RetroRemix** [comment]
> yeah i have the same issue with the same map

Someone in discord by the name Brent helped me with this and since I did it it fixed carrier. Go to Options, then Advanced video options, and then turn off Shader Preload and It should fix it. Worked fine for me
![image](https://user-images.githubusercontent.com/83484042/116823039-f449e800-ab36-11eb-80a6-23c650e1e7ce.png)

**Comment by diamante0018** [comment]
What Brent days is correct. Closing this
